### ISSUE TITLE
Users Can Start Their Car

### ISSUE THREAD

**Issue by jonathanphtran** [jonathanphtran/driving-game#6]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] select the car container
- [x] move the car a few pixels
- [x] make that happen every 16 milliseconds
